name = "hono-remix-vite-on-cloudflare"
compatibility_date = "2024-05-12"
pages_build_output_dir = "./build/client"

[vars]
MY_VAR = "Hello from Cloudflare"
SECRET = "12086fb500fc4bafae7d660773b554c6"


# Automatically place your workloads in an optimal location to minimize latency.
# If you are running back-end logic in a Worker, running it closer to your back-end infrastructure
# rather than the end user may result in better performance.
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
[placement]
mode = "smart"

[[kv_namespaces]]
binding = "kv"
id = "12086fb500fc4bafae7d660773b554c6"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"